name: Check

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: server/go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          working-directory: server

  go-generate-diff:
    name: go generate 差分確認
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: server/go.mod
      - name: go generate
        working-directory: server
        run: go generate ./...
      - name: 差分確認
        run: git --no-pager diff --exit-code

  go-test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: server/go.mod
      - name: go test
        working-directory: server
        run: go test ./...
